# Generated by Django 6.0.4 on 2026-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к картинке'),
        ),
    ]
