# Generated by Django 6.0.4 on 2026-04-24 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название мема')),
                ('image_path', models.CharField(help_text='Например: img/mems/exam.jpg', max_length=255, verbose_name='Путь к картинке')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто запостил')),
            ],
            options={
                'verbose_name': 'Мем',
                'verbose_name_plural': 'Мемы',
            },
        ),
    ]
